package it.gurzau_rovellini.casino.Java;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.GapContent;

/**
 *
 * @author teoro
 */
public class Casino extends javax.swing.JFrame {
    GestioneAccount ga;
    GestioneCrediti gc;
    
    SlotMachine sm;
    BlackJack bj;
    
    int whatopen = 0; //0 nulla--1 slot--2 blackjack
    boolean isOpen = false;
    boolean isLogged = false;
    
    /**
     * Creates new form Casino
     */
    public Casino() {
        initComponents();
        ga=new GestioneAccount();
        gc=new GestioneCrediti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        pnlTab0 = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNumCredits = new javax.swing.JLabel();
        btnBlackJack = new javax.swing.JButton();
        btnSlotMachine = new javax.swing.JButton();
        btnCredits = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnRegistrati = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblConfirm = new javax.swing.JLabel();
        btnAccedi = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        pnlTab1 = new javax.swing.JPanel();
        pnlButtons1 = new javax.swing.JPanel();
        lblUser1 = new javax.swing.JLabel();
        lblCredits1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblNumCredits1 = new javax.swing.JLabel();
        btnBlackJack1 = new javax.swing.JButton();
        btnSlotMachine1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblNumeroCard = new javax.swing.JLabel();
        lblProprietarioCard = new javax.swing.JLabel();
        lblCVV = new javax.swing.JLabel();
        btnAddCrediti = new javax.swing.JButton();
        btnRmvCrediti = new javax.swing.JButton();
        sldSoldi = new javax.swing.JSlider();
        pnlCard = new javax.swing.JPanel();
        txtProprietarioCard = new javax.swing.JTextField();
        txtNumeroCard = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        spnSlider = new javax.swing.JSpinner();
        btnSaldoCarta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 400));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane.setAlignmentX(0.0F);
        tabbedPane.setAlignmentY(0.0F);
        tabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabbedPane.setName(""); // NOI18N

        pnlTab0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlButtons.setBackground(new java.awt.Color(51, 51, 51));
        pnlButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User:");
        pnlButtons.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 30));

        lblCredits.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblCredits.setForeground(new java.awt.Color(255, 255, 255));
        lblCredits.setText("Credits:");
        pnlButtons.add(lblCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, 30));

        lblName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Guest");
        pnlButtons.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 30));

        lblNumCredits.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblNumCredits.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCredits.setText("0");
        pnlButtons.add(lblNumCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        btnBlackJack.setBackground(new java.awt.Color(240, 127, 1));
        btnBlackJack.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnBlackJack.setText("Black Jack");
        btnBlackJack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackJackActionPerformed(evt);
            }
        });
        pnlButtons.add(btnBlackJack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 200, 60));

        btnSlotMachine.setBackground(new java.awt.Color(240, 127, 1));
        btnSlotMachine.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnSlotMachine.setText("Slot Machine");
        btnSlotMachine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSlotMachine.setIconTextGap(10);
        btnSlotMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlotMachineActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSlotMachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 200, 60));

        btnCredits.setBackground(new java.awt.Color(240, 127, 1));
        btnCredits.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnCredits.setText("Credito");
        btnCredits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCredits.setIconTextGap(10);
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, 200, 60));

        btnEsci.setBackground(new java.awt.Color(153, 153, 153));
        btnEsci.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnEsci.setText("Esci");
        btnEsci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });
        pnlButtons.add(btnEsci, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\utente.png"));
        pnlButtons.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\Risorsa 2.png"));
        pnlButtons.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 40, 40));

        pnlTab0.add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        lblTitle.setFont(new java.awt.Font("Perpetua Titling MT", 1, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Benvenuto al Casinò MM");

        btnRegistrati.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnRegistrati.setText("Registrati");
        btnRegistrati.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistratiActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblPassword.setText("Password:");

        txtUsername.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblConfirm.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblConfirm.setText("Se non hai ancora un profilo registrati !");

        btnAccedi.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnAccedi.setText("Accedi");
        btnAccedi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccediActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrati)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnAccedi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername))
                        .addGap(60, 60, 60)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccedi)
                    .addComponent(btnRegistrati)
                    .addComponent(lblConfirm))
                .addGap(89, 89, 89))
        );

        pnlTab0.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 400));

        tabbedPane.addTab("tab1", pnlTab0);

        pnlTab1.setPreferredSize(new java.awt.Dimension(800, 400));

        pnlButtons1.setBackground(new java.awt.Color(51, 51, 51));
        pnlButtons1.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlButtons1.setName(""); // NOI18N
        pnlButtons1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblUser1.setText("User:");
        pnlButtons1.add(lblUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 30));

        lblCredits1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblCredits1.setForeground(new java.awt.Color(255, 255, 255));
        lblCredits1.setText("Credits:");
        pnlButtons1.add(lblCredits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, 30));

        lblName1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Guest");
        pnlButtons1.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 30));

        lblNumCredits1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblNumCredits1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCredits1.setText("0");
        pnlButtons1.add(lblNumCredits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        btnBlackJack1.setBackground(new java.awt.Color(240, 127, 1));
        btnBlackJack1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnBlackJack1.setText("Black Jack");
        btnBlackJack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackJack1ActionPerformed(evt);
            }
        });
        pnlButtons1.add(btnBlackJack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 200, 60));

        btnSlotMachine1.setBackground(new java.awt.Color(240, 127, 1));
        btnSlotMachine1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnSlotMachine1.setText("Slot Machine");
        btnSlotMachine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlotMachine1ActionPerformed(evt);
            }
        });
        pnlButtons1.add(btnSlotMachine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 200, 60));

        btnHome.setBackground(new java.awt.Color(240, 127, 1));
        btnHome.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlButtons1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, 200, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\utente.png"));
        pnlButtons1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\Risorsa 2.png"));
        pnlButtons1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 40));

        lblTitle1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 30)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("GESTIONE DEI CREDITI");
        lblTitle1.setAlignmentY(0.0F);

        lblNumeroCard.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblNumeroCard.setText("Numero carta:");

        lblProprietarioCard.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblProprietarioCard.setText("Nome proprietario:");

        lblCVV.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblCVV.setText("CVV:");

        btnAddCrediti.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnAddCrediti.setText("Aggiungi Crediti");
        btnAddCrediti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCreditiActionPerformed(evt);
            }
        });

        btnRmvCrediti.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnRmvCrediti.setText("Preleva Crediti");
        btnRmvCrediti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvCreditiActionPerformed(evt);
            }
        });

        sldSoldi.setMajorTickSpacing(10);
        sldSoldi.setMinorTickSpacing(5);
        sldSoldi.setPaintLabels(true);
        sldSoldi.setPaintTicks(true);
        sldSoldi.setValue(0);
        sldSoldi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldSoldiStateChanged(evt);
            }
        });

        txtProprietarioCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txtNumeroCard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txtCVV.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCVV, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(txtNumeroCard)
            .addComponent(txtProprietarioCard, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                .addComponent(txtProprietarioCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtNumeroCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spnSlider.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        spnSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSliderStateChanged(evt);
            }
        });

        btnSaldoCarta.setText("Saldo Carta");
        btnSaldoCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoCartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTab1Layout = new javax.swing.GroupLayout(pnlTab1);
        pnlTab1.setLayout(pnlTab1Layout);
        pnlTab1Layout.setHorizontalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addComponent(pnlButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTab1Layout.createSequentialGroup()
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProprietarioCard)
                                    .addComponent(lblNumeroCard)
                                    .addComponent(lblCVV))
                                .addGap(34, 34, 34)
                                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTab1Layout.createSequentialGroup()
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnSlider)
                                    .addComponent(btnSaldoCarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)
                                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlTab1Layout.createSequentialGroup()
                                        .addComponent(btnRmvCrediti)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddCrediti))
                                    .addComponent(sldSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTab1Layout.setVerticalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTab1Layout.createSequentialGroup()
                        .addComponent(lblProprietarioCard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblNumeroCard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldSoldi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRmvCrediti)
                    .addComponent(btnAddCrediti)
                    .addComponent(btnSaldoCarta))
                .addGap(33, 33, 33))
        );

        tabbedPane.addTab("tab2", pnlTab1);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackJackActionPerformed
        // TODO add your handling code here:
        if (lblName.getText().equals("Guest")) {
            JOptionPane.showMessageDialog(null, "Devi prima effettuare l'accesso ad un profilo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        } else if (!isOpen){
            whatopen = 2;
            bj=new BlackJack();
            bj.setLblName(lblName);
            bj.setLblNumCredits(lblNumCredits);
            bj.setVisible(true);
            //this.setVisible(false);
            isOpen=true;
        }
    }//GEN-LAST:event_btnBlackJackActionPerformed

    private void btnSlotMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlotMachineActionPerformed
        // TODO add your handling code here:
        //se non è stato effettuato il login: errore
        if (lblName.getText().equals("Guest")) {
            JOptionPane.showMessageDialog(null, "Devi prima effettuare l'accesso ad un profilo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        } else if (!isOpen){
            whatopen = 1;
            sm=new SlotMachine();
            sm.setLblName(lblName);
            sm.setLblNumCredits(lblNumCredits);
            sm.setVisible(true);
            //this.setVisible(false);
            isOpen=true;
        }
    }//GEN-LAST:event_btnSlotMachineActionPerformed

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
        // TODO add your handling code here:
        //se non è stato effettuato il login: errore
        if (lblName.getText().equals("Guest")) {
            JOptionPane.showMessageDialog(null, "Devi prima effettuare l'accesso ad un profilo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        } else if (!isOpen) {
            tabbedPane.setSelectedIndex(1);
        }  
    }//GEN-LAST:event_btnCreditsActionPerformed

    private void btnRegistratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistratiActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        if(!isLogged){
            if (ga.register(new Account(username, password)) == 0){
                // Registrazione eseguita
                lblConfirm.setText("Registrazione effettuata");
                txtUsername.setText("");
                txtPassword.setText("");
            }
            else if(ga.register(new Account(username, password)) == 1){
                // utente già esistente, esegui la Registrazione
                JOptionPane.showMessageDialog(null, "Nome utente già esistente, creane uno nuovo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                lblConfirm.setText("Nome utente già esistente, creane uno nuovo !!!");
                txtUsername.setText("");
                txtPassword.setText("");
            }
            else{
                // lunghezza password sbagliata
                JOptionPane.showMessageDialog(null, "Lunghezza password errata, MIN=6 - MAX=16 !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                lblConfirm.setText("Immetti una password (MIN.6 MAX.16");
                txtPassword.setText("");
            }
        }else JOptionPane.showMessageDialog(null, "Accesso già effettuato, per cambiare profilo esci da quello in uso !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnRegistratiActionPerformed

    private void btnAccediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccediActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        //se non si ha ancora effettuato il login
        if (!isLogged) {
            //se il file Account.txt contiene l'username immesso
            if (ga.contains(username)) {
                //se tutte le credenziali immesse corrispondono a quelle presenti nel file Account.txt
                if (ga.login(new Account(username, password))) {
                    //login effettuato, variabile login già effettuato messa a true per impedire di effettuare un nuovo accesso senza prima uscire
                    isLogged=true;
                    lblConfirm.setText("Login effettuato");
                    txtUsername.setText("");
                    txtPassword.setText("");
                    lblName.setText(username);
                    lblNumCredits.setText("" + ga.getCrediti(username));
                    lblName1.setText(username);
                    lblNumCredits1.setText("" + ga.getCrediti(username));
                } else {
                    //password errata
                    JOptionPane.showMessageDialog(null, "Password errata !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                    txtPassword.setText("");
                }
            } else {
                //L'account non esiste
                JOptionPane.showMessageDialog(null, "Account insesistente, registrati !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                lblConfirm.setText("Account inesistente, registrati !!!");
                txtUsername.setText("");
                txtPassword.setText("");
            }
        //se è già stato eseguito il login
        } else {
            JOptionPane.showMessageDialog(null, "Accesso già effettuato, per cambiare profilo esci da quello in uso !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAccediActionPerformed

    private void btnBlackJack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackJack1ActionPerformed
        // TODO add your handling code here:
        if (lblName.getText().equals("Guest")) {
            JOptionPane.showMessageDialog(null, "Devi prima effettuare l'accesso ad un profilo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        } else if (!isOpen){
            tabbedPane.setSelectedIndex(0);
            whatopen = 2;
            bj=new BlackJack();
            bj.setLblName(lblName);
            bj.setLblNumCredits(lblNumCredits);
            bj.setVisible(true);
            //this.setVisible(false);
            isOpen=true;
        }
    }//GEN-LAST:event_btnBlackJack1ActionPerformed

    private void btnSlotMachine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlotMachine1ActionPerformed
        // TODO add your handling code here:
        //se non è stato effettuato il login: errore
        if (lblName.getText().equals("Guest")) {
            JOptionPane.showMessageDialog(null, "Devi prima effettuare l'accesso ad un profilo !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        //se non è gia aperta la finestra Slot Machine
        } else if (!isOpen){
            tabbedPane.setSelectedIndex(0);
            whatopen = 1;
            sm=new SlotMachine();
            sm.setLblName(lblName);
            sm.setLblNumCredits(lblNumCredits);
            sm.setVisible(true);
            isOpen=true;
        }
    }//GEN-LAST:event_btnSlotMachine1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAddCreditiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreditiActionPerformed
        // TODO add your handling code here:
        String proprietario = txtProprietarioCard.getText();
        String numeroCarta = txtNumeroCard.getText();
        String cvv = txtCVV.getText();
        int soldi = sldSoldi.getValue();
        
        //se tutti i campi della carta di credito sono già presenti nel file
        if (gc.contains(proprietario, numeroCarta, cvv)) {
            // aggiorna saldo nel file
            if(gc.puoPrelevare(numeroCarta, soldi)){
                gc.preleva(numeroCarta, soldi);
                char mod = '+';
                if (ga.contains(lblName1.getText())){
                    ga.setCrediti(lblName1.getText(), soldi, mod);
                }
                lblNumCredits1.setText("" + (Integer.parseInt(lblNumCredits1.getText()) + soldi));
                lblNumCredits.setText("" + (Integer.parseInt(lblNumCredits.getText()) + soldi));
            }else JOptionPane.showMessageDialog(null, "Non hai abbastanza soldi sulla carta di credito per effettuare la transazione !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
        //se corrisponde solo il numero di carta
        } else if (gc.contains(numeroCarta)) {
            JOptionPane.showMessageDialog(null, "Proprietario e/o CVV errati !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
            return;
        //se non è presente nessuno campo della carta di credito all'interno del file
        } else {
            // crea una nuova carta e la aggiunge nel file
            if (gc.aggiungi(new CartaCredito(proprietario, numeroCarta, cvv, CartaCredito.DEFAULT_SOLDI - soldi))){
                char mod = '+';
                if (ga.contains(lblName1.getText())){
                    ga.setCrediti(lblName1.getText(), soldi, mod);
                }
                lblNumCredits1.setText("" + (Integer.parseInt(lblNumCredits1.getText()) + soldi));
                lblNumCredits.setText("" + (Integer.parseInt(lblNumCredits.getText()) + soldi));
            //se il numero di carta o il CVV non hanno la lunghezza prefissata
            } else {
                JOptionPane.showMessageDialog(null, "Lunghezza numero carta e/o lunghezza CVV errata !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        // Cambia le label riferitosi al credito
        
    }//GEN-LAST:event_btnAddCreditiActionPerformed

    private void btnRmvCreditiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvCreditiActionPerformed
        // TODO add your handling code here:
        String proprietario = txtProprietarioCard.getText();
        String numeroCarta = txtNumeroCard.getText();
        String cvv = txtCVV.getText();
        int soldi = sldSoldi.getValue();
        //se ci sono abbastanza crediti nell'account in uso
        if (ga.creditiSufficienti(lblName1.getText(), soldi)) {
            //se tutti i campi della carta di credito sono già presenti nel file
            if (gc.contains(proprietario, numeroCarta, cvv)) {
                // aggiorna saldo nel file
                gc.deposita(numeroCarta, soldi);
            //se corrisponde solo il numero di carta
            } else if (gc.contains(numeroCarta)) {
                JOptionPane.showMessageDialog(null, "Proprietario e/o CVV errati !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                return;
            //se non è presente nessuno campo della carta di credito all'interno del file
            } else {
                // crea una nuova carta e la aggiunge nel file
                if (gc.aggiungi(new CartaCredito(proprietario, numeroCarta, cvv, CartaCredito.DEFAULT_SOLDI + soldi))) {
                //se il numero di carta o il CVV non hanno la lunghezza prefissata
                } else {
                    JOptionPane.showMessageDialog(null, "Lunghezza numero carta e/o lunghezza CVV errata !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            // Cambia le label riferitosi al credito
            lblNumCredits1.setText("" + (Integer.parseInt(lblNumCredits1.getText()) - soldi));
            lblNumCredits.setText("" + (Integer.parseInt(lblNumCredits.getText()) - soldi));
            char mod = '-';

            if (ga.contains(lblName1.getText())){
                ga.setCrediti(lblName1.getText(), soldi, mod);

            }
        //se non ci sono abbastanza crediti nell'account in uso: errore
        } else JOptionPane.showMessageDialog(null, "Non hai abbastanza crediti sull'account per effettuare la transazione !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnRmvCreditiActionPerformed

    private void sldSoldiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldSoldiStateChanged
        // TODO add your handling code here:
        //aggiorna lo spinner se viene modificato il valore sullo slider
        spnSlider.setValue(sldSoldi.getValue());
    }//GEN-LAST:event_sldSoldiStateChanged

    private void spnSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSliderStateChanged
        // TODO add your handling code here:
        //se il valore immesso all'interno dello spinnner è minore di 0
        if ((int)spnSlider.getValue() < 0 ){
            spnSlider.setValue(0);
        //se il valore immesso all'interno dello spinnner è maggiore di 100
        } else if ((int)spnSlider.getValue() > 100) {
            spnSlider.setValue(100);
        }
        //aggiorna lo slider se viene modificato il valore all'interno dello spinner
        sldSoldi.setValue((int)spnSlider.getValue());
    }//GEN-LAST:event_spnSliderStateChanged

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        // TODO add your handling code here:
        //cambia le label rimettendo quelle predefinite
        if (!isOpen) {  
            //variabile login già effettuato rimessa a false  
            isLogged = false;        
            //cambia le label rimettendo quelle predefinite 
            lblName.setText("Guest");        
            lblNumCredits.setText("0");   
            lblName1.setText("Guest");        
            lblNumCredits1.setText("0");     
        } else JOptionPane.showMessageDialog(null, "Prima di uscire dal profilo chiudi la Slot Machine !!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEsciActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        GestioneAccount ganewFocus=new GestioneAccount();
        lblNumCredits.setText(""+ganewFocus.getCrediti(lblName.getText()));
        lblNumCredits1.setText(""+ganewFocus.getCrediti(lblName1.getText()));
        switch(whatopen){
            case 0:
                break;
            case 1:
                if (isOpen) this.isOpen = sm.isOpen;
                break;
            case 2:
                if (isOpen) this.isOpen = bj.isOpen;
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnSaldoCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoCartaActionPerformed
        // TODO add your handling code here:
        String proprietario = txtProprietarioCard.getText();
        String numeroCarta = txtNumeroCard.getText();
        String cvv = txtCVV.getText();
        
        if (gc.contains(proprietario, numeroCarta, cvv)) {
            JOptionPane.showMessageDialog(null, "Il saldo rimanente sulla sua carta è di :" + gc.getSoldi(numeroCarta) + "€", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(null, "Abbiamo appena riscontrato un errore con la sua banca!!!", "Attenzione", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSaldoCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccedi;
    private javax.swing.JButton btnAddCrediti;
    private javax.swing.JButton btnBlackJack;
    private javax.swing.JButton btnBlackJack1;
    private javax.swing.JButton btnCredits;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegistrati;
    private javax.swing.JButton btnRmvCrediti;
    private javax.swing.JButton btnSaldoCarta;
    private javax.swing.JButton btnSlotMachine;
    private javax.swing.JButton btnSlotMachine1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblCredits1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNumCredits;
    private javax.swing.JLabel lblNumCredits1;
    private javax.swing.JLabel lblNumeroCard;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProprietarioCard;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlButtons1;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlTab0;
    private javax.swing.JPanel pnlTab1;
    private javax.swing.JSlider sldSoldi;
    private javax.swing.JSpinner spnSlider;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtNumeroCard;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtProprietarioCard;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
