package it.gurzau_rovellini.casino.Java;

import java.awt.image.renderable.RenderableImageProducer;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author teoro
 */
public class SlotMachine extends javax.swing.JFrame {
    GestioneAccount ga;
    ImageIcon[] images={
            new ImageIcon("src\\test\\Images\\slotmachine\\anguria.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\arancia.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\ciliegia.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\limone.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\mela.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\prugna.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\uva.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\cuore.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\bar.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\campana.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\cavallo.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\moneta.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\diamante.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\quadrifoglio.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\sette.jpg"),
            new ImageIcon("src\\test\\Images\\slotmachine\\bonus.jpg") };
    
    Spin spin1, spin2, spin3, spin4, spin5;
    int initialCredits;
    Boolean isOpen=true;
    
    
    
    /**
     * Creates new form SlotMachine
     */
    public SlotMachine() {
        initComponents();
        ga=new GestioneAccount();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlImages = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnSpin = new javax.swing.JButton();
        btnPlus1 = new javax.swing.JButton();
        btnPlus50 = new javax.swing.JButton();
        btnPlus10 = new javax.swing.JButton();
        btnPlus500 = new javax.swing.JButton();
        btnMinus1 = new javax.swing.JButton();
        btnMinus10 = new javax.swing.JButton();
        btnMinus50 = new javax.swing.JButton();
        btnMinus500 = new javax.swing.JButton();
        lblBet = new javax.swing.JLabel();
        lblTitleBet = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNumCredits = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWinnings = new javax.swing.JLabel();
        lblNumWinnings = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setTitle("Slot Machine");
        setBounds(new java.awt.Rectangle(0, 0, 800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(0, 153, 51));

        pnlImages.setBackground(new java.awt.Color(0, 153, 51));

        lblImage1.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\slotmachine\\anguria.jpg"));
        lblImage1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        lblImage2.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\slotmachine\\cavallo.jpg"));
        lblImage2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        lblImage3.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\slotmachine\\sette.jpg"));
        lblImage3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        lblImage4.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\slotmachine\\diamante.jpg"));
        lblImage4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        lblImage5.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\slotmachine\\limone.jpg"));
        lblImage5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        javax.swing.GroupLayout pnlImagesLayout = new javax.swing.GroupLayout(pnlImages);
        pnlImages.setLayout(pnlImagesLayout);
        pnlImagesLayout.setHorizontalGroup(
            pnlImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 50, Short.MAX_VALUE)
                .addComponent(lblImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlImagesLayout.setVerticalGroup(
            pnlImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblImage5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlButtons.setBackground(new java.awt.Color(0, 153, 51));

        btnSpin.setBackground(new java.awt.Color(255, 102, 0));
        btnSpin.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnSpin.setText("SPIN");
        btnSpin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpinActionPerformed(evt);
            }
        });

        btnPlus1.setBackground(new java.awt.Color(255, 204, 0));
        btnPlus1.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnPlus1.setText("+1");
        btnPlus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlus1.setPreferredSize(new java.awt.Dimension(83, 83));
        btnPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus1ActionPerformed(evt);
            }
        });

        btnPlus50.setBackground(new java.awt.Color(255, 204, 0));
        btnPlus50.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnPlus50.setText("+50");
        btnPlus50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlus50.setPreferredSize(new java.awt.Dimension(83, 83));
        btnPlus50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus50ActionPerformed(evt);
            }
        });

        btnPlus10.setBackground(new java.awt.Color(255, 204, 0));
        btnPlus10.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnPlus10.setText("+10");
        btnPlus10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus10ActionPerformed(evt);
            }
        });

        btnPlus500.setBackground(new java.awt.Color(255, 204, 0));
        btnPlus500.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnPlus500.setText("+500");
        btnPlus500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlus500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus500ActionPerformed(evt);
            }
        });

        btnMinus1.setBackground(new java.awt.Color(255, 204, 0));
        btnMinus1.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnMinus1.setText("-1");
        btnMinus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus1ActionPerformed(evt);
            }
        });

        btnMinus10.setBackground(new java.awt.Color(255, 204, 0));
        btnMinus10.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnMinus10.setText("-10");
        btnMinus10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus10ActionPerformed(evt);
            }
        });

        btnMinus50.setBackground(new java.awt.Color(255, 204, 0));
        btnMinus50.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnMinus50.setText("-50");
        btnMinus50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus50ActionPerformed(evt);
            }
        });

        btnMinus500.setBackground(new java.awt.Color(255, 204, 0));
        btnMinus500.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        btnMinus500.setText("-500");
        btnMinus500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus500ActionPerformed(evt);
            }
        });

        lblBet.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
        lblBet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBet.setText("0");

        lblTitleBet.setFont(new java.awt.Font("Stencil", 0, 40)); // NOI18N
        lblTitleBet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleBet.setText("BET");

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus50, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus500, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblTitleBet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus50, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlus10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus500, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlButtonsLayout.createSequentialGroup()
                        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlus50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus50, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus500, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus500, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                        .addComponent(lblTitleBet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlUser.setBackground(new java.awt.Color(51, 51, 51));
        pnlUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlUser.setAlignmentX(0.0F);
        pnlUser.setAlignmentY(0.0F);

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User:");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Guest");

        lblNumCredits.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNumCredits.setForeground(new java.awt.Color(255, 255, 255));
        lblNumCredits.setText("0");

        lblCredits.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCredits.setForeground(new java.awt.Color(255, 255, 255));
        lblCredits.setText("Credits:");

        jLabel2.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\utente.png"));

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\test\\Images\\Risorsa 2.png"));

        lblWinnings.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        lblWinnings.setForeground(new java.awt.Color(255, 255, 255));
        lblWinnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinnings.setText("Credits won:");

        lblNumWinnings.setFont(new java.awt.Font("Stencil", 0, 30)); // NOI18N
        lblNumWinnings.setForeground(new java.awt.Color(255, 255, 255));
        lblNumWinnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumWinnings.setText("0");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNumCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(lblWinnings, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumWinnings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNumCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumWinnings, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWinnings, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setLblName(JLabel lblName) {
        this.lblName.setText(lblName.getText());
    }

    public void setLblNumCredits(JLabel lblNumCredits) {
        this.lblNumCredits.setText(lblNumCredits.getText());
        initialCredits=Integer.parseInt(lblNumCredits.getText());
    }
    
    /**
     * Metodo per avviare la slotmachine
     * @param evt bottone cliccato 
     */
    private void btnSpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpinActionPerformed
        // TODO add your handling code here:
        //se i crediti del profilo sono esauriti viene visualizzato il popup
        if (lblNumCredits.getText().equals("0") && lblBet.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Hai esaurito i crediti !!!", "Attenzione", JOptionPane.WARNING_MESSAGE);
        }
        //se la puntata è 0 non esegue spin
        if (lblBet.getText().equals("0")) {
            return;
        }

        spin1=new Spin(images, lblImage1, 200);
        spin2=new Spin(images, lblImage2, 300);
        spin3=new Spin(images, lblImage3, 400);
        spin4=new Spin(images, lblImage4, 500);
        spin5=new Spin(images, lblImage5, 600);
        
        spin1.start();
        spin2.start();
        spin3.start();
        spin4.start();
        spin5.start();
     
        //attesa che i thread abbiano terminato la loro esecuzione e verifica delle condizioni di vittoria
        ConditionSlotMachine csm=new ConditionSlotMachine(spin1, spin2, spin3, spin4, spin5, lblBet, lblNumCredits, lblNumWinnings, btnSpin, initialCredits);
        csm.start();
    }//GEN-LAST:event_btnSpinActionPerformed

    private void btnPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus1ActionPerformed
        // TODO add your handling code here:
        //controllo crediti account e crediti parziali vinti con slot machine
        if (Integer.parseInt(lblNumCredits.getText())>=1) {
            int tmp=Integer.parseInt(lblBet.getText())+1;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())-1;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnPlus1ActionPerformed

    private void btnPlus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus10ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblNumCredits.getText())>=10) {
            int tmp=Integer.parseInt(lblBet.getText())+10;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())-10;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnPlus10ActionPerformed

    private void btnPlus50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus50ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblNumCredits.getText())>=50) {
            int tmp=Integer.parseInt(lblBet.getText())+50;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())-50;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnPlus50ActionPerformed

    private void btnPlus500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus500ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblNumCredits.getText())>=500) {
            int tmp=Integer.parseInt(lblBet.getText())+500;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())-500;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnPlus500ActionPerformed

    private void btnMinus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus1ActionPerformed
        // TODO add your handling code here:
        //controllo che la puntata sia maggiore o uguale a quanto si vuole sottrarre ad essa
        if (Integer.parseInt(lblBet.getText())>=1) {
            int tmp=Integer.parseInt(lblBet.getText())-1;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())+1;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnMinus1ActionPerformed

    private void btnMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus10ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblBet.getText())>=10) {
            int tmp=Integer.parseInt(lblBet.getText())-10;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())+10;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnMinus10ActionPerformed

    private void btnMinus50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus50ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblBet.getText())>=50) {
            int tmp=Integer.parseInt(lblBet.getText())-50;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())+50;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnMinus50ActionPerformed

    private void btnMinus500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus500ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblBet.getText())>=500) {
            int tmp=Integer.parseInt(lblBet.getText())-500;
            lblBet.setText(String.valueOf(tmp));
            
            tmp=Integer.parseInt(lblNumCredits.getText())+500;
            lblNumCredits.setText(String.valueOf(tmp));
        }
    }//GEN-LAST:event_btnMinus500ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ga.setCrediti(lblName.getText(), Integer.parseInt(lblNumCredits.getText()));
        isOpen=false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachine().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinus1;
    private javax.swing.JButton btnMinus10;
    private javax.swing.JButton btnMinus50;
    private javax.swing.JButton btnMinus500;
    private javax.swing.JButton btnPlus1;
    private javax.swing.JButton btnPlus10;
    private javax.swing.JButton btnPlus50;
    private javax.swing.JButton btnPlus500;
    private javax.swing.JButton btnSpin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBet;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumCredits;
    private javax.swing.JLabel lblNumWinnings;
    private javax.swing.JLabel lblTitleBet;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblWinnings;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlImages;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlUser;
    // End of variables declaration//GEN-END:variables

}